### ISSUE TITLE
`scikit-build` pulling in `cmake` & `make`

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/scikit-build-feedstock#69]
Typically recipes need to add `cmake` & `make` to `requirements/build` when needed. This is done in part to avoid inadvertently linking to shared libraries `cmake` & `make` might pull into the environment and instead using them strictly as command line tools

Naively would have thought `scikit-build` would rely on the user to install these requirements, but noticed both are included in `requirements/run`

https://github.com/conda-forge/scikit-build-feedstock/blob/f22722fca3979fc2587cbbfb51592a26a391c105/recipe/meta.yaml#L27-L29

Am curious if there is more context behind including `cmake` & `make` in `scikit-build`'s `requirements/run`. Is this just trying to convey these requirements somehow? Or is there more to the story?

**Comment by henryiii** [comment]
You cannot use scikit-build without cmake. It would be pointless. Conda forces `CMAKE_GENERATOR` to make, regardless of if it's installed, so you get a very unpleasant surprise if you only include ninja and scikit-build and expect it to work like it would if you weren't in conda. You can't forcibly include cmake & ninja on PyPI, since not all platforms are supported by binary wheels, but conda is a binary-only platform, so those should always be available.

So yes, this is entirely to try to make sure this works out of the box without requiring a user to inject extra requirements just to make it work (cmake & make), and to keep it better line with that you'd see in pyproject.toml - you should never see cmake & ninja there (scikit-build-core has a proper solution for this).

Scikit-build is in requirements/build for recipes, so things in it shouldn't leak, including things in scikit-build's requirement/run, I'd have expected. And cmake/make should not have much in the way of shared libraries.

**Comment by jakirkham** [comment]
Agree `cmake` & `make` need to be available somehow.

> Scikit-build is in requirements/build for recipes, so things in it shouldn't leak, including things in scikit-build's requirement/run, I'd have expected.

This is interesting. So are we saying `scikit-build` should be in `requirements/build` instead of `requirements/host`? Asking since [a bunch of recipes do the latter]( https://github.com/search?q=org%3Aconda-forge+path%3Arecipe%2Fmeta.yaml+scikit-build&type=code ). Also curious on how this change would work as I thought (maybe wrongly?) that `scikit-build` should be next to the `python` it is installing into, but maybe there is another way to do this?

> And cmake/make should not have much in the way of shared libraries.

Unfortunately this isn't the case. With `cmake`, it has [a bunch of requirements]( https://github.com/conda-forge/cmake-feedstock/blob/4943f9dd8496beff534c14899fe593f99c4cbf7a/recipe/meta.yaml#L45-L55 ) (directly and indirectly). Also this has bitten conda-forge in the past (conda-build 2) and was the reason for separating `requirements/host` from `requirements/build`.

**Comment by henryiii** [comment]
Ahh, yes, this has to be listed in host, I think. Hmm, that does complicate things.
